# biodata diri

print("NamaLengkap")
namaLengkap = input()
print("Umur")
umur = int(input())
print("TinggiBadan")
tinggiBadan = float(input())
print("Apakah kamu Mahasiswa Aktif?")
statusMahasiswa = (input().strip().lower() == 'true')
print("Apakah Kamu Mahasiswa Aktif?" + str(statusMahasiswa))
print("AsalDaerah")
asalDaerah = input()
print("Jurusan")
jurusan = input()
print("Hobi")
hobi = input()
print("Minat")
minat = input()
print("Pengisian Biodata selesai, Terimakasih telah mengisi biodata")

print("===== BIODATA DIRI =====")
print(f"Nama Lengkap     : {namaLengkap}")
print(f"Umur             : {umur} tahun")
print(f"Tinggi Badan     : {tinggiBadan} cm")
print(f"Mahasiswa Aktif  : {statusMahasiswa}")
print(f"Asal Daerah      : {asalDaerah}")
print(f"Jurusan          : {jurusan}")
print(f"Hobi             : {hobi}")